name: "Setup ActiveState CLI"
description: "Sets up the ActiveState CLI in your GitHub Actions workflow."
inputs:
  version:
    description: "Version of the state CLI to install"
    required: false
  channel:
    description: "Channel to download the state CLI from"
    required: false
    default: "release"
  # activestate-api-key:
  #   description: "API key used to authenticate to the ActiveState platform"
  #   required: true
runs:
  using: "composite"
  steps:
  - name: "Install state CLI"
    if: runner.os == 'Linux' || runner.os == 'macOS'
    shell: "bash"
    run: |
      installArgs=""
      if [ "${{ inputs.version }}" ]; then
        installArgs="-v ${{ inputs.version }} "
      fi
      CHANNEL="${{ inputs.channel }}"
      installArgs="${installArgs}-b $CHANNEL"
      sh <(curl -q https://platform.activestate.com/dl/cli/install.sh) $installArgs
      export PATH="$HOME/.local/ActiveState/StateTool/$CHANNEL/bin:$PATH"



