name: "integration tests"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        channel: beta
    - name: run help command
      run: state --help
  test-macos-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        activestate-api-key: foobar
    - name: run help command
      run: state --help
  test-windows-latest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        activestate-api-key: foobar
    - name: run help command
      run: state --help
